//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBuy_elctronics_DB
{
    using System;
    
    public partial class cGet_AllOrders
    {
        public Nullable<int> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string CategoryName { get; set; }
        public string BrandName { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public int ItemOrderID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
