//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBuy_elctronics_DB
{
    using System;
    
    public partial class cGet_AllFeedback
    {
        public string LoginName { get; set; }
        public string CategoryName { get; set; }
        public string BrandName { get; set; }
        public string Feedbackdesc { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
