//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBuy_elctronics_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Inventories = new HashSet<Inventory>();
            this.InventoryAudits = new HashSet<InventoryAudit>();
            this.ItemOrders = new HashSet<ItemOrder>();
        }
    
        public int ItemID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string ItemName { get; set; }
        public string ItemDesc { get; set; }
        public string ImageURL { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual ICollection<InventoryAudit> InventoryAudits { get; set; }
        public virtual ICollection<ItemOrder> ItemOrders { get; set; }
    }
}
