//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBuy_elctronics_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logindetail
    {
        public Logindetail()
        {
            this.FeedbackDescs = new HashSet<FeedbackDesc>();
            this.Loginaudits = new HashSet<Loginaudit>();
            this.Loginprofiles = new HashSet<Loginprofile>();
            this.Queries = new HashSet<Query>();
            this.Questionbases = new HashSet<Questionbase>();
        }
    
        public int Loginid { get; set; }
        public string Loginname { get; set; }
        public string Password { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Logintype { get; set; }
        public Nullable<int> Squestionid { get; set; }
        public string Sanswer { get; set; }
        public Nullable<int> Firstlogin { get; set; }
        public Nullable<System.DateTime> Passmodifieddate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<FeedbackDesc> FeedbackDescs { get; set; }
        public virtual ICollection<Loginaudit> Loginaudits { get; set; }
        public virtual ICollection<Loginprofile> Loginprofiles { get; set; }
        public virtual ICollection<Query> Queries { get; set; }
        public virtual ICollection<Questionbase> Questionbases { get; set; }
    }
}
