//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBuy_elctronics_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solution
    {
        public int SolutionID { get; set; }
        public Nullable<int> QueryId { get; set; }
        public Nullable<System.DateTime> SolvedDate { get; set; }
        public string Solution1 { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Query Query { get; set; }
    }
}
