//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBuy_elctronics_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalOrder
    {
        public TotalOrder()
        {
            this.ItemOrders = new HashSet<ItemOrder>();
        }
    
        public int OrderID { get; set; }
        public Nullable<int> LoginID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> TotalAmount { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ItemOrderId { get; set; }
    
        public virtual ICollection<ItemOrder> ItemOrders { get; set; }
    }
}
